name: CI
on: 
    push:
        paths:
        - 'data/tokens.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
      #Using sd-transform to convert Figma Tokens JSON to match Style Dictionary
      - run: npx tokens-studio/sd-transforms  
      ##### Transform Figma Tokens JSON to something Style Dictionary can read
      #####- run: npx token-transformer data/tokens.json tokens/preformatted-tokens.json
      # Convert tokens according to Style Dictionary config
      #- run: npx style-dictionary build --config config.json
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
